## **Neighborhood segmentation and clustering 2**
The second part of this project is dedicated, to merge Toronto's neighbourhoods and geographical coordinates dataframes, in order to match each neigbourhood with its longitude/latitudes coordinates, using the postal code as key for both dataframes.

In [3]:
#import pandas library
import pandas as pd

# allocate the cleaned dataframe from the first part of this project, and allocat it to df_neig
df_neig=pd.read_csv('Toronto.csv', header=0,index_col=0)

# check the dataframe
df_neig.head(10)

  Postcode           Borough                     Neighbourhood
0      M3A        North York                         Parkwoods
1      M4A        North York                  Victoria Village
2      M5A  Downtown Toronto                      Harbourfront
3      M6A        North York  Lawrence Heights, Lawrence Manor
4      M7A      Queen's Park                      Not assigned
5      M9A      Queen's Park                      Queen's Park
6      M1B       Scarborough                    Rouge, Malvern
7      M3B        North York                   Don Mills North
8      M4B         East York   Woodbine Gardens, Parkview Hill
9      M5B  Downtown Toronto          Ryerson, Garden District

In [4]:
# allocate the provided Geospatial_Coordinates.csv to dataframe called df_coord
df_coord = pd.read_csv('Geospatial_Coordinates.csv', header=0,index_col=0)

#check the dataframe
df_coord.head()

              Latitude  Longitude
Postal Code
M1B          43.806686 -79.194353
M1C          43.784535 -79.160497
M1E          43.763573 -79.188711
M1G          43.770992 -79.216917
M1H          43.773136 -79.239476

in order to be able to merge both dataframes, we need to have an identical column name as an id for both, hence we need replace "Postale Code" in `df_coord` , by "Postcode" as per `df_neig`

In [5]:
# change the collumn name in 
idx= df_coord.index
idx.rename('Postcode', inplace=True)

now we will proceed with merging both dataframes in order to allocate `latitudes/longitudes` to each postal code.

In [6]:
df_merge_col = pd.merge(df_neig, df_coord, on='Postcode')
df_merge_col.head(12)

,Postcode,Borough,Neighbourhood,Latitude,Longitude
0,M3A,North York,Parkwoods,43.753259,-79.329656
1,M4A,North York,Victoria Village,43.725882,-79.315572
2,M5A,Downtown Toronto,Harbourfront,43.654260,-79.360636
3,M6A,North York,"Lawrence Heights, Lawrence Manor",43.718518,-79.464763
4,M7A,Queen's Park,Not assigned,43.662301,-79.389494
5,M9A,Queen's Park,Queen's Park,43.667856,-79.532242
6,M1B,Scarborough,"Rouge, Malvern",43.806686,-79.194353
7,M3B,North York,Don Mills North,43.745906,-79.352188
8,M4B,East York,"Woodbine Gardens, Parkview Hill",43.706397,-79.309937
9,M5B,Downtown Toronto,"Ryerson, Garden District",43.657162,-79.378937
10,M6B,North York,Glencairn,43.709577,-79.445073
11,M9B,Etobicoke,"Cloverdale, Islington, Martin Grove, Princess ...",43.650943,-79.554724

We will save the dataframe for the third part of the project, in which we will explore toronto's neighbourhoods using folium and matplotlib.

In [34]:
# export the dataframe as CSV file for the second part of the assignment
df_toronto.to_csv('Toronto_geo_coord.csv')